print("I like cookies")
print("Hello I'm here for git practice - Local")
print("Sometimes i think about how dogs are better than cats")
print("Sometimes I think about the dream of being a walmart greeter")
print("Hello I'm here for git practice - Remote")
print("Sometimes I realize I want to just play with electronics all day.")
print("Sometimes I realize that students don't do anything I want them to")
print("Added during merge")
print("Remote end")
print("Local end")
