print("Hello I'm here for git practice - Local")
print("Sometimes I think about the dream of being a walmart greeter")
print("Hello I'm here for git practice - Remote")
print("Sometimes I realize I want to just play with electronics all day.")
print("Added during merge")
print("Local end")
